spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:vaadin-demo;
        driverClassName: org.h2.Driver
        spring:
            datasource:
                username: sa
                password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect